//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.8689
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback RegisterNewCustomerOperationCompleted;
    
    private System.Threading.SendOrPostCallback LoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback RegisterRestaurantOperationCompleted;
    
    private System.Threading.SendOrPostCallback DisplayDashboardOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateRestaurantQRCodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback EditRestaurantQRCodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback ResetPasswordOperationCompleted;
    
    /// <remarks/>
    public Service1() {
        this.Url = "http://37.97.194.163/TagnEatWCF/Service1.svc";
    }
    
    /// <remarks/>
    public event RegisterNewCustomerCompletedEventHandler RegisterNewCustomerCompleted;
    
    /// <remarks/>
    public event LoginCompletedEventHandler LoginCompleted;
    
    /// <remarks/>
    public event RegisterRestaurantCompletedEventHandler RegisterRestaurantCompleted;
    
    /// <remarks/>
    public event DisplayDashboardCompletedEventHandler DisplayDashboardCompleted;
    
    /// <remarks/>
    public event CreateRestaurantQRCodeCompletedEventHandler CreateRestaurantQRCodeCompleted;
    
    /// <remarks/>
    public event EditRestaurantQRCodeCompletedEventHandler EditRestaurantQRCodeCompleted;
    
    /// <remarks/>
    public event ResetPasswordCompletedEventHandler ResetPasswordCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RegisterNewCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RegisterNewCustomer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tittle, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string firstname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lastname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailaddress, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phonenumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordconfirm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string country, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string city, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string town, out int RegisterNewCustomerResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RegisterNewCustomerResultSpecified) {
        object[] results = this.Invoke("RegisterNewCustomer", new object[] {
                    tittle,
                    firstname,
                    lastname,
                    emailaddress,
                    phonenumber,
                    password,
                    passwordconfirm,
                    country,
                    city,
                    town});
        RegisterNewCustomerResult = ((int)(results[0]));
        RegisterNewCustomerResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void RegisterNewCustomerAsync(string tittle, string firstname, string lastname, string emailaddress, string phonenumber, string password, string passwordconfirm, string country, string city, string town) {
        this.RegisterNewCustomerAsync(tittle, firstname, lastname, emailaddress, phonenumber, password, passwordconfirm, country, city, town, null);
    }
    
    /// <remarks/>
    public void RegisterNewCustomerAsync(string tittle, string firstname, string lastname, string emailaddress, string phonenumber, string password, string passwordconfirm, string country, string city, string town, object userState) {
        if ((this.RegisterNewCustomerOperationCompleted == null)) {
            this.RegisterNewCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterNewCustomerOperationCompleted);
        }
        this.InvokeAsync("RegisterNewCustomer", new object[] {
                    tittle,
                    firstname,
                    lastname,
                    emailaddress,
                    phonenumber,
                    password,
                    passwordconfirm,
                    country,
                    city,
                    town}, this.RegisterNewCustomerOperationCompleted, userState);
    }
    
    private void OnRegisterNewCustomerOperationCompleted(object arg) {
        if ((this.RegisterNewCustomerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RegisterNewCustomerCompleted(this, new RegisterNewCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void Login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out int LoginResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool LoginResultSpecified) {
        object[] results = this.Invoke("Login", new object[] {
                    username,
                    password});
        LoginResult = ((int)(results[0]));
        LoginResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void LoginAsync(string username, string password) {
        this.LoginAsync(username, password, null);
    }
    
    /// <remarks/>
    public void LoginAsync(string username, string password, object userState) {
        if ((this.LoginOperationCompleted == null)) {
            this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
        }
        this.InvokeAsync("Login", new object[] {
                    username,
                    password}, this.LoginOperationCompleted, userState);
    }
    
    private void OnLoginOperationCompleted(object arg) {
        if ((this.LoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RegisterRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RegisterRestaurant([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string restaurantname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string restaurantcontact, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string restaurantlocation, out int RegisterRestaurantResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RegisterRestaurantResultSpecified) {
        object[] results = this.Invoke("RegisterRestaurant", new object[] {
                    username,
                    restaurantname,
                    restaurantcontact,
                    restaurantlocation});
        RegisterRestaurantResult = ((int)(results[0]));
        RegisterRestaurantResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void RegisterRestaurantAsync(string username, string restaurantname, string restaurantcontact, string restaurantlocation) {
        this.RegisterRestaurantAsync(username, restaurantname, restaurantcontact, restaurantlocation, null);
    }
    
    /// <remarks/>
    public void RegisterRestaurantAsync(string username, string restaurantname, string restaurantcontact, string restaurantlocation, object userState) {
        if ((this.RegisterRestaurantOperationCompleted == null)) {
            this.RegisterRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterRestaurantOperationCompleted);
        }
        this.InvokeAsync("RegisterRestaurant", new object[] {
                    username,
                    restaurantname,
                    restaurantcontact,
                    restaurantlocation}, this.RegisterRestaurantOperationCompleted, userState);
    }
    
    private void OnRegisterRestaurantOperationCompleted(object arg) {
        if ((this.RegisterRestaurantCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RegisterRestaurantCompleted(this, new RegisterRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DisplayDashboard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Xml.XmlElement DisplayDashboard([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username) {
        object[] results = this.Invoke("DisplayDashboard", new object[] {
                    username});
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public void DisplayDashboardAsync(string username) {
        this.DisplayDashboardAsync(username, null);
    }
    
    /// <remarks/>
    public void DisplayDashboardAsync(string username, object userState) {
        if ((this.DisplayDashboardOperationCompleted == null)) {
            this.DisplayDashboardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayDashboardOperationCompleted);
        }
        this.InvokeAsync("DisplayDashboard", new object[] {
                    username}, this.DisplayDashboardOperationCompleted, userState);
    }
    
    private void OnDisplayDashboardOperationCompleted(object arg) {
        if ((this.DisplayDashboardCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DisplayDashboardCompleted(this, new DisplayDashboardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CreateRestaurantQRCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void CreateRestaurantQRCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlTime, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlDay, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlDigitalMenu, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlUrls, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlOther, out int CreateRestaurantQRCodeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CreateRestaurantQRCodeResultSpecified) {
        object[] results = this.Invoke("CreateRestaurantQRCode", new object[] {
                    XmlTime,
                    XmlDay,
                    XmlDigitalMenu,
                    XmlUrls,
                    XmlOther});
        CreateRestaurantQRCodeResult = ((int)(results[0]));
        CreateRestaurantQRCodeResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void CreateRestaurantQRCodeAsync(string XmlTime, string XmlDay, string XmlDigitalMenu, string XmlUrls, string XmlOther) {
        this.CreateRestaurantQRCodeAsync(XmlTime, XmlDay, XmlDigitalMenu, XmlUrls, XmlOther, null);
    }
    
    /// <remarks/>
    public void CreateRestaurantQRCodeAsync(string XmlTime, string XmlDay, string XmlDigitalMenu, string XmlUrls, string XmlOther, object userState) {
        if ((this.CreateRestaurantQRCodeOperationCompleted == null)) {
            this.CreateRestaurantQRCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRestaurantQRCodeOperationCompleted);
        }
        this.InvokeAsync("CreateRestaurantQRCode", new object[] {
                    XmlTime,
                    XmlDay,
                    XmlDigitalMenu,
                    XmlUrls,
                    XmlOther}, this.CreateRestaurantQRCodeOperationCompleted, userState);
    }
    
    private void OnCreateRestaurantQRCodeOperationCompleted(object arg) {
        if ((this.CreateRestaurantQRCodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateRestaurantQRCodeCompleted(this, new CreateRestaurantQRCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/EditRestaurantQRCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void EditRestaurantQRCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlTimeEdit, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlDayEdit, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlDigitalMenuEdit, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XmlOtherEdit, out int EditRestaurantQRCodeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EditRestaurantQRCodeResultSpecified) {
        object[] results = this.Invoke("EditRestaurantQRCode", new object[] {
                    XmlTimeEdit,
                    XmlDayEdit,
                    XmlDigitalMenuEdit,
                    XmlOtherEdit});
        EditRestaurantQRCodeResult = ((int)(results[0]));
        EditRestaurantQRCodeResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void EditRestaurantQRCodeAsync(string XmlTimeEdit, string XmlDayEdit, string XmlDigitalMenuEdit, string XmlOtherEdit) {
        this.EditRestaurantQRCodeAsync(XmlTimeEdit, XmlDayEdit, XmlDigitalMenuEdit, XmlOtherEdit, null);
    }
    
    /// <remarks/>
    public void EditRestaurantQRCodeAsync(string XmlTimeEdit, string XmlDayEdit, string XmlDigitalMenuEdit, string XmlOtherEdit, object userState) {
        if ((this.EditRestaurantQRCodeOperationCompleted == null)) {
            this.EditRestaurantQRCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditRestaurantQRCodeOperationCompleted);
        }
        this.InvokeAsync("EditRestaurantQRCode", new object[] {
                    XmlTimeEdit,
                    XmlDayEdit,
                    XmlDigitalMenuEdit,
                    XmlOtherEdit}, this.EditRestaurantQRCodeOperationCompleted, userState);
    }
    
    private void OnEditRestaurantQRCodeOperationCompleted(object arg) {
        if ((this.EditRestaurantQRCodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EditRestaurantQRCodeCompleted(this, new EditRestaurantQRCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ResetPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void ResetPassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phonenumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userpassword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string newpassword, out int ResetPasswordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ResetPasswordResultSpecified) {
        object[] results = this.Invoke("ResetPassword", new object[] {
                    username,
                    phonenumber,
                    userpassword,
                    newpassword});
        ResetPasswordResult = ((int)(results[0]));
        ResetPasswordResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void ResetPasswordAsync(string username, string phonenumber, string userpassword, string newpassword) {
        this.ResetPasswordAsync(username, phonenumber, userpassword, newpassword, null);
    }
    
    /// <remarks/>
    public void ResetPasswordAsync(string username, string phonenumber, string userpassword, string newpassword, object userState) {
        if ((this.ResetPasswordOperationCompleted == null)) {
            this.ResetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetPasswordOperationCompleted);
        }
        this.InvokeAsync("ResetPassword", new object[] {
                    username,
                    phonenumber,
                    userpassword,
                    newpassword}, this.ResetPasswordOperationCompleted, userState);
    }
    
    private void OnResetPasswordOperationCompleted(object arg) {
        if ((this.ResetPasswordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ResetPasswordCompleted(this, new ResetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void RegisterNewCustomerCompletedEventHandler(object sender, RegisterNewCustomerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RegisterNewCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RegisterNewCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int RegisterNewCustomerResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool RegisterNewCustomerResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int LoginResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool LoginResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void RegisterRestaurantCompletedEventHandler(object sender, RegisterRestaurantCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RegisterRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RegisterRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int RegisterRestaurantResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool RegisterRestaurantResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void DisplayDashboardCompletedEventHandler(object sender, DisplayDashboardCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DisplayDashboardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DisplayDashboardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlElement)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void CreateRestaurantQRCodeCompletedEventHandler(object sender, CreateRestaurantQRCodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateRestaurantQRCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateRestaurantQRCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int CreateRestaurantQRCodeResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool CreateRestaurantQRCodeResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void EditRestaurantQRCodeCompletedEventHandler(object sender, EditRestaurantQRCodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EditRestaurantQRCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EditRestaurantQRCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int EditRestaurantQRCodeResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool EditRestaurantQRCodeResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void ResetPasswordCompletedEventHandler(object sender, ResetPasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ResetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ResetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int ResetPasswordResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool ResetPasswordResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}
